services:
  wordpress:
    image: wordpress:latest
    container_name: amsterdam-events-wp
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 0
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content-custom:/var/www/html/wp-content/themes/custom
      - ./wp-config-local.php:/var/www/html/wp-config-local.php
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: amsterdam-events-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: amsterdam-events-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress_password
    depends_on:
      - db
    restart: unless-stopped

volumes:
  wordpress_data:
  db_data: 